app/urls.py
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from app.views.quiz import PlayQuizView, ResultsView, QuizzesView, MyQuizzesView, QuizTermsView

app_name = 'app'

urlpatterns = [
    path('playquiz/<int:id>', PlayQuizView.as_view(), name='playquiz'),
    path('quizzes/<int:id>', QuizzesView.as_view(), name='quizzes'),
    path('myquizzes/', MyQuizzesView.as_view(), name='myquizzes'),
    path('playquiz/results/<int:pk>', ResultsView.as_view(), name='results'),
    path('quizterms/<int:id>', QuizTermsView.as_view(), name='quizterms'),
]

app/views/quiz.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic
from app.models import Question, QuizResult, UserQuiz, Quiz
from engage.models import SadbhavanaScore
from django.utils import translation
from django.conf import settings
from django.db.models import F

class PlayQuizView(generic.ListView):
    template_name = 'quiz/playquiz.html'
    model = Question

    # Save quiz result
    def post(self, request, **kwargs):
        data = dict(request.POST)

        res = UserQuiz(user_id=request.user.id, quiz_id=kwargs['id'], comments='')
        res.save()

        score, answers, results, total = 0, [], [], 0
        for q in Question.objects.filter(is_active=True, quiz_id=kwargs['id']):

            _ans = "NA"
            total += q.score
            if "choice"+str(q.id) in data:
                _ans = data["choice"+str(q.id)][0]
                if str(q.answer) == _ans:
                    score += q.score
            results.append(QuizResult(user_quiz_id=res.id, question_id=q.id, answer=_ans))

        QuizResult.objects.bulk_create(results)

        res.score = score

        res.total_score = 10
        res.save()

        # Update sadbhavana score table
        points = score
        if request.user.id is not None :
            objUser = SadbhavanaScore.objects.filter(user_id=request.user.id)

            if objUser:
                SadbhavanaScore.objects.filter(user_id=request.user.id).update(points=F('points')+points)
            else:
                user = SadbhavanaScore(user_id=request.user.id,points=points)
                user.save()

        context = {}  #  set your context

        return HttpResponseRedirect('results/' + str(res.id))

    # get quiz
    # def get_queryset(self):
    def get(self, *args, **kwargs):

        quiz = Quiz.objects.filter(is_active=True, id=kwargs['id'])

        for q in quiz:
            is_random = q.show_random
        if is_random == True:
            questions = Question.objects.all().filter(quiz_id=kwargs['id'], is_active=True).order_by('?')[:10]
        else:
            questions = Question.objects.all().filter(quiz_id=kwargs['id'], is_active=True).order_by('id')[:10]

        context = {'questions': questions, "quiz": quiz[0], 'baseURL': settings.BASE_URL, 'navBar': 'play'}

        return render(self.request, 'quiz/playquiz.html', context)


class QuizzesView(generic.DetailView):
    model = Quiz
    template_name = 'quiz/quizzes.html'

    # Get all quiz
    def get(self, *args, **kwargs):
        if translation.LANGUAGE_SESSION_KEY in self.request.session: 
            lang_id = self.request.session[translation.LANGUAGE_SESSION_KEY]
        else:
            lang_id = 'en'

        quizzes = Quiz.objects.raw(""" SELECT id, name, caption, description, image FROM app_quiz WHERE is_active = True AND lang = '{}' """.format(lang_id))

        quiz_id = kwargs['id']
        metadata = """ SELECT id, image, name, description FROM app_quiz WHERE id = {} """.format(quiz_id)
        metaData = Quiz.objects.raw(metadata)

        context = {
            'quizzes': quizzes,
            'metaData': metaData[0],
            'baseURL': settings.BASE_URL,
            'navBar': 'play'
        }
        return render(self.request, 'quiz/quizzes.html', context)

# Get terms and conditions for quiz
class QuizTermsView(LoginRequiredMixin, generic.DetailView):
    model = Quiz
    template_name = 'quiz/quiz-terms-and-conditions.html'

    def get(self, *args, **kwargs):
        quizzes = Quiz.objects.raw("""SELECT id, name, caption, description, image as image FROM app_quiz WHERE is_active = True AND id = {}""".format(kwargs['id']))

        context = {
            'quizterms': quizzes[0], 
            'baseURL': settings.BASE_URL,
            'navBar': 'play'
        }
        return render(self.request, 'quiz/quiz-terms-and-conditions.html', context)


class MyQuizzesView(LoginRequiredMixin, generic.DetailView):
    model = UserQuiz
    template_name = 'quiz/myquizzes.html'

    # get login user attended quiz
    def get(self, *args, **kwargs):

        q = """ SELECT au.id, aq.name, quiz_id, score, au.pub_date, image as image FROM app_userquiz au inner join app_quiz aq on aq.id=au.quiz_id WHERE user_id = {} order by au.pub_date desc""".format(self.request.user.id)
        results = UserQuiz.objects.raw(q)

        context = {
            'results': results,
            'user': self.request.user, 
            'baseURL': settings.BASE_URL,
            'navBar': 'play'
        }
        return render(self.request, 'quiz/myquizzes.html', context)


class ResultsView(generic.DetailView):
    model = QuizResult
    template_name = 'quiz/quiz-results.html'

    # show result of quiz after finishing quiz
    def get(self, *args, **kwargs):

        result = UserQuiz.objects.filter(pk=kwargs['pk'], user_id=self.request.user.id)
        answers = QuizResult.objects.filter(user_quiz_id=result[0].id)
        quiz = Quiz.objects.filter(id=result[0].quiz_id)

        context = {
            'result': result[0],
            'answers': answers,
            'quiz': quiz[0], 
            'baseURL': settings.BASE_URL,
            'navBar': 'play'
        }
        return render(self.request, 'quiz/quiz-results.html', context)

# not in use
@login_required
def result(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    context = {
        'latest_question_list': latest_question_list,
    }

    return render(request, 'quiz/playquiz.html', context)


app/templates/quiz/myquizzes.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% load i18n %}
  {% load static %}

  {% block meta %}
  <meta charset="utf-8" />
  <title>Sadbhavana - My Quizzes</title>
  <meta name="description" content="" />
  {% endblock %}

</head>

<body>

  {% block content %}

  <section class="page-header">
    <div class="container">

      <h1 class="trn">{% trans "My Quizzes" %}</h1>

      <!-- breadcrumbs -->
      <ol class="breadcrumb">
        <li><a href="{% url 'home' %}" class="trn">{% trans "Home" %}</a></li>
        <!-- <li><a href="#">Pages</a></li> -->
        <li class="active trn">{% trans "My Quizzes" %}</li>
      </ol><!-- /breadcrumbs -->

    </div>
  </section>
  <!-- /PAGE HEADER -->

  <!-- -->
  <section>
    <div class="container">
      {% if not results %}
      <h3>{% trans "You haven't attended any quiz!" %}</h3>
      <!-- {% get_static_prefix as STATIC_PREFIX %} -->
      {% else %}
      {% for result in results %}
      <div class="row">
        <!-- item -->
        <div class="col-md-2">
          <!-- company logo -->
          <img src='https://rgf-bucket.s3.ap-south-1.amazonaws.com/{{ result.image }}' class="img-fluid" alt="Quiz logo">
        </div>
        <div class="col-md-10">
          <!-- company detail -->
          <h4 class="mb-10">{{result.quiz.name}}</h4>
          <p><b>TAKEN ON : </b> {{result.pub_date}}</p>
          <p><b>SCORE : </b> {{result.score}}/{{result.total_score}}</p>
        </div>
      </div><!-- /item -->
      <hr />
      {% endfor %}
      {% endif %}
    </div>
  </section>
  <!-- / -->
  {% endblock %}

  {% block includes %}
  <!-- SCROLL TO TOP -->
  <a href="#" id="toTop"></a>


  <!-- PRELOADER -->
  <div id="preloader">
    <div class="inner">
      <span class="loader"></span>
    </div>
  </div><!-- /PRELOADER -->


  <!-- JAVASCRIPT FILES -->
  <script>var plugin_path = "{% static 'assets/plugins/index.html' %}";</script>
  <script src="{% static 'assets/plugins/jquery/jquery-3.3.1.min.js' %}"></script>

  <script src="{% static 'assets/js/scripts.js' %}"></script>

  <script src="{% static 'assets/js/login-register.js' %}"></script>
  <script type="text/javascript" src="{% static 'assets/js/jquery.validate.min.js' %}"></script>

  <!-- TRASLATIONS -->
  <script src="{% static 'assets/js/jquery.translate.js' %}"></script>
  <script src="{% static 'assets/languages/translations.js' %}"></script>
  <script src="{% static 'assets/js/translater.js' %}"></script>

  <!-- PAGE LEVEL SCRIPTS -->
  <script>

    /**
      Checkbox on "I agree" modal Clicked!
    **/
    jQuery("#terms-agree").click(function () {
      jQuery('#termsModal').modal('toggle');

      // Check Terms and Conditions checkbox if not already checked!
      if (!jQuery("#checked-agree").checked) {
        jQuery("input.checked-agree").prop('checked', true);
      }

    });
  </script>
  {% endblock %}
  
</body>

</html>

app/templates/quiz/playquiz.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% load i18n %}
  {% load static %}

  {% block meta %}
  <meta charset="utf-8" />
  <title>Sadbhavana - {{ quiz.name }}</title>
  <meta name="description" content="" />
  <link href="{% static 'assets/css/play-quiz.css' %}" rel="stylesheet" type="text/css" />
  {% endblock %}

</head>

<style>
  .ques-radio {
    text-align: center;
    vertical-align: middle;
  }

  .qPanel {
    display: none;
  }

  .showing {
    display: contents;
    background: #FFF;
  }

  .qButton {
    cursor: pointer;
  }

  .hidden {
    display: none;
  }

  .spacer {
    flex: 0 auto;
    display: flex;
    width: 100%;
  }

  .pagination-ques {
    display: inline-block;
    padding-inline-start: 20px;
  }

  .pagination-ques a {
    color: black;
    float: left;
    padding: 8px 16px;
    text-decoration: none;
    transition: background-color .3s;
  }

  .pagination-ques a.current {
    background-color: #149dc5;
    color: white;
  }

  .pagination-ques a:hover:not(.current) {
    background-color: #ddd;
  }

  .page-link {
    cursor: pointer;
  }

  #myProgress {
    width: 100%;
    background-color: #ddd;
  }

  #myBar {
    width: 100%;
    height: 30px;
    background-color: #4CAF50;
  }
  .table td,
  .table th {
    border: none;
  }

  .options {
    border: 1px solid gray;
    border-radius: 10px;
    padding: 10px;
    cursor: pointer;
  }

  input[type="radio"] {
    cursor: pointer;
  }
</style>

<body>

  {% block content %}

  <section class="page-header">
    <div class="container">

      <h1>{{quiz.name}}</h1>

      <!-- breadcrumbs -->
      <ol class="breadcrumb">
        <li><a href="{% url 'home' %}" class="trn">{% trans "Home" %}</a></li>
        <!-- <li><a href="#">Pages</a></li> -->
        <li><a href="{% url 'app:quizzes' 1 %}" class="active trn">{% trans "Quizzes" %}</a></li>
        <li>{{quiz.name}}</li>
      </ol><!-- /breadcrumbs -->

    </div>
  </section>
  <!-- /PAGE HEADER -->


  <!-- -->
  <section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <table class="table nobottommargin quiz-table" align="center" style="background-color:#FFF;">
            <form method="post" name="answers" id="answers" action="">
              {% csrf_token %}
              <input type='hidden' value='{{quiz.id}}' name='quizId'>

              {% for question in questions %}
              <tbody class="qPanel">
                <tr valign="top">
                  <input type='hidden' value='1' name="qid[1]">

                  {% if question.question_text != '' and question.question_image == '' %}
                    <th align="left">
                      <h4><span style="color:#000;">{{forloop.counter}}. </span>{{ question.question_text }}</h4>
                    </th>
                  {% elif question.question_text == '' and question.question_image %}
                    <th align="center"> <!-- class="text-center" -->
                      <span>{{forloop.counter}}. </span><img class="quiz-img" src="https://rgf-bucket.s3.amazonaws.com/{{question.question_image}}" />
                    </th>
                  {% else %}
                  <th align="center"> <!-- class="text-center" -->
                    <span>{{forloop.counter}}. </span><img class="quiz-img" src="https://rgf-bucket.s3.amazonaws.com/{{question.question_image}}" />
                    <h4>{{ question.question_text }}</h4>
                  </th>
                  {% endif %}


                </tr>
                <tr valign="top">
                  <td><label class="element-animation1 btn btn-lg btn-block options" onclick="checkForAnswer(event)" for="{{ question.id }}-Option A">
                    <input type="radio" name="choice{{ question.id }}" value='Option A' id='{{ question.id }}-Option A' style="visibility: hidden;">{{ question.option_a }}
                  </label></td>
                </tr>
                <tr valign="top">
                  <td><label class="element-animation2 btn btn-lg btn-block options" onclick="checkForAnswer(event)" for="{{ question.id }}-Option B">
                    <input type="radio" name="choice{{ question.id }}" value='Option B' id='{{ question.id }}-Option B' style="visibility: hidden;">{{ question.option_b }}
                  </label></td>
                </tr>
                <tr valign="top">
                  <td><label class="element-animation3 btn btn-lg btn-block options" onclick="checkForAnswer(event)" for="{{ question.id }}-Option C">
                    <input type="radio" name="choice{{ question.id }}" value='Option C' id='{{ question.id }}-Option C' style="visibility: hidden;">{{ question.option_c }}
                  </label></td>
                </tr>
                <tr valign="top">
                  <td><label class="element-animation4 btn btn-lg btn-block options" onclick="checkForAnswer(event)" for="{{ question.id }}-Option D">
                    <input type="radio" name="choice{{ question.id }}" value='Option D' id='{{ question.id }}-Option D' style="visibility: hidden;">{{ question.option_d }}
                  </label></td>
                </tr>
                <tr><td><small>{{ question.desclaimer }}</small></td></tr>
              </tbody>

              {% endfor %}
              <tbody style="border:none;">
                <tr>
                  <td colspan="2" align="right">
                    <ul class="pagination">
                      <nav aria-label="Page navigation example">
                        <ul class="pagination-ques">

                          {% for question in questions %}
                          <a class="qButton hidden">{{forloop.counter}}</a>
                          {% endfor %}

                          <a style="color:#FFF;margin: 0px 0 5px 5px;" class="btn btn-info navbutton"
                            onclick="nav(1)">{% trans "Next" %}</a>
                          <span class="spacer"></span>
                        </ul>
                      </nav>
                    </ul>
                  </td>
                </tr>
              </tbody>
            </form>
          </table>
        </div>
      </div>
    </div>
  </section>
  <!-- / -->

  {% endblock %}

  {% block includes %}
  <!-- SCROLL TO TOP -->
  <a href="#" id="toTop"></a>


  <!-- PRELOADER -->
  <div id="preloader">
    <div class="inner">
      <span class="loader"></span>
    </div>
  </div><!-- /PRELOADER -->


  <!-- JAVASCRIPT FILES -->
  <script>var plugin_path = "{% static 'assets/plugins/index.html' %}";</script>
  <script src="{% static 'assets/plugins/jquery/jquery-3.3.1.min.js' %}"></script>

  <script src="{% static 'assets/js/scripts.js' %}"></script>

  <!-- <script src="{% static 'assets/js/play-quiz.js' %}"></script> -->

  <!-- TRASLATIONS -->
  <script src="{% static 'assets/js/jquery.translate.js' %}"></script>
  <script src="{% static 'assets/languages/translations.js' %}"></script>
  <script src="{% static 'assets/js/translater.js' %}"></script>

  <script>
    var numQuestions, navs;

    function init() {

      numQuestions = $(".qButton").length;
      navs = $(".navbutton");

      show(0);
    }

    window.onload = init;
    var currentQuestion = 0;

    $(".qPanel").first().addClass(" showing");
    $(".qButton").first().addClass(" current");

    function show(i) {

      $(".current").first().addClass("qButton");
      $(".showing").first().addClass("qPanel");

      $(".qPanel").removeClass("showing");
      $(".qPanel").each(function (index) {
        if (index == i) {
          $(this).addClass("showing");
        }
      });

      $(".qButton").removeClass("current");
      $(".qButton").each(function (index) {

        if (index == i) {
          $(this).addClass("current");
        }
      });

      //navs[0].style.cursor = i === numQuestions - 1 ? 'not-allowed' : '';

      if (i === numQuestions - 1) {
        //navs[0].style.cursor = 'not-allowed';
        $(".navbutton").removeAttr("onclick");
        $(".navbutton").attr("onclick", 'finishQuiz()');
        $(".navbutton").text('{% trans "FINISH" %}');
      } else {
        navs[0].style.cursor = '';
      }

      //navs[1].style.cursor = i === numQuestions - 1 ? 'not-allowed' : '';

      currentQuestion = i;

    }
    function nav(offset) {
      $(".options").attr('onclick', 'checkForAnswer(event)');
      $(".options").css('cursor', 'pointer');
      $("input[type=radio]").attr('disabled', false);

      var targetQuestion = currentQuestion + offset;
      if (targetQuestion >= 0 && targetQuestion < $(".qButton").length)
        show(targetQuestion);

    }

    function finishQuiz() {
      $("input[type=radio]").attr('disabled', false);
      console.log('Quiz finished');
      setTimeout(function () {
        $("#answers").submit();
      }, 1000)
    }

    function checkForAnswer(event) {
      $('.options').css('background-color', '');
      $('.options').css('color', '');

      {% for question in questions %}

      if (event.target.htmlFor == '{{question.id}}-{{question.answer}}') {
        $(event.target).css('background-color', '#008000');
        $(event.target).css('color', '#fff');

        $(".options").removeAttr('onclick');
        $(".options").css('cursor', 'not-allowed');

        setTimeout(function () {
          $("input[type=radio]").attr('disabled', true);
        }, 100)

        return;
      }
      {% endfor %}

	    else {
        $(event.target).css('background-color', '#FF0000');
        $(event.target).css('color', '#fff');
      }

      $(".options").removeAttr('onclick');
      $(".options").css('cursor', 'not-allowed');
      setTimeout(function () {
        $("input[type=radio]").attr('disabled', true);
      }, 100)

      setTimeout(function () {
        $("input[type=radio]").attr('disabled', true);
        $(".options").each(function () {
          var quesNo = this.htmlFor.split('-');
          var quesClicked = event.target.htmlFor.split('-');

          {% for question in questions %}
          if (quesNo[0] == quesClicked[0] && this.htmlFor == '{{question.id}}-{{question.answer}}') {
            $(this).css('background-color', '#008000');
            $(this).css('color', '#fff');
            return;
          }
          {% endfor %}
        });

      }, 1000);

    }

  </script>
  {% endblock %}

</body>

</html>

app/templates/quiz/quiz-terms-and-conditions.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% load i18n %}
  {% load static %}

  {% block meta %}
  <meta charset="utf-8" />
  <title>Sadbhavana - Quiz Terms and Conditions</title>
  <meta name="description" content="" />
  {% endblock %}

</head>

<body>

  {% block content %}

  <section class="page-header">
    <div class="container">

      <h1 class="trn">{% trans "Terms And Conditions" %}</h1>

      <!-- breadcrumbs -->
      <ol class="breadcrumb">
        <li><a href="{% url 'home' %}" class="trn">{% trans "Home" %}</a></li>
        <li class="active">{{ quizterms.name }}</li>
      </ol><!-- /breadcrumbs -->

    </div>
  </section>
  <!-- /PAGE HEADER -->

  <!-- -->
  <section>
    <div class="container">

      <div class="row">
        <!-- QUIZ-TERMS AND CONDITONS -->
        <div class="col-md-12 col-sm-12">
          <ol class="static lang-en en">
            <li>There is no entry fee and no purchase necessary to enter this quiz.</li>
            <li>By entering this quiz, an entrant is indicating his/her agreement to be bound by these terms and
              conditions.</li>
            <li>The decision of our team is final and no correspondence in this regard is entertained.</li>
            <li>No prize- cash or otherwise, is distributed for this quiz.</li>
            <li>This quiz is aimed at informative and entertainment purposes only.</li>
          </ol>
          <ol class="static lang-hn hn">
            <li>यह प्रश्नोत्तरी पूर्णतया नि: शुल्क है|</li>
            <li>इस प्रश्नोत्तरी में भाग लेने पर आवेदक इसके नियमों से बाध्य होंगे|</li>
            <li>किसी भी असहमति की स्थिति में हमारे निर्णायक मंडल का निर्णय अंतिम होगा|</li>
            <li>इस प्रश्नोत्तरी से कोई भी पुरस्कार संलग्न नहीं है|</li>
            <li>यह प्रश्नोत्तरी मात्र ज्ञानवर्धन एवं मनोरंजन के लिए है|</li>
          </ol>
          <ol class="static lang-pn pn">
            <li>ਇਸ ਕਵਿਜ਼ ਵਿੱਚ ਭਾਗ ਲੈਣ ਦੀ ਕੋਈ ਐਂਟਰੀ ਫੀਸ ਯਾ ਖਰੀਦ ਨਹੀਂ ਮੰਗੀ ਜਾਵੇਗੀ।</li>
            <li>ਇਸ ਕਵਿਜ਼ ਵਿੱਚ ਭਾਗ ਲੈਣ ਵਾਲੇ ਨਿਮਨਲਿਖਿਤ ਨਿਯਮਾਂ ਦੇ ਬੱਝੇ ਹੋਣਗੇ।</li>
            <li>ਕਿਸੇ ਵੀ ਮਤਭੇਦ ਦੀ ਸਥਿਤੀ ਵਿੱਚ, ਸਾਡੀ ਟੀਮ ਦਾ ਫ਼ੈਸਲਾ ਅੰਤਮ ਹੋਵੇਗਾ ਅਤੇ ਇਸ ਬਾਰੇ ਕੋਈ ਵੀ ਪੁੱਛਗਿੱਛ ਨਹੀਂ ਕੀਤੀ
              ਜਾਵੇਗੀ।</li>
            <li>ਇਸ ਕਵਿਜ਼ ਨਾਲ ਕੋਈ ਇਨਾਮ ਨਹੀਂ ਜੁੜੇ ਹੋਏ ਹਨ।</li>
            <li>ਇਹ ਕਵਿਜ਼ ਸਿਰਫ਼ ਗਿਆਨ ਵਧਾਉਣ ਅਤੇ ਮਨੋਰੰਜਨ ਲਈ ਹੈ।</li>
          </ol>

          <div class="text-center">
            <a href="{% url 'app:playquiz' quizterms.id %}"><button
                class="btn btn-primary trn">{% trans "Proceed" %}</button></a>&nbsp;
            <a href="javascript: window.history.back();"><button class="btn btn-secondary trn">{% trans "Go Back" %}</button></a>
          </div>

        </div>
        <!-- /QUIZ-TERMS AND CONDITONS -->
      </div>
    </div>
  </section>
  <!-- / -->

  {% endblock %}

  {% block includes %}
  <!-- SCROLL TO TOP -->
  <a href="#" id="toTop"></a>


  <!-- PRELOADER -->
  <div id="preloader">
    <div class="inner">
      <span class="loader"></span>
    </div>
  </div><!-- /PRELOADER -->


  <!-- JAVASCRIPT FILES -->
  <script>var plugin_path = "{% static 'assets/plugins/index.html' %}";</script>
  <script src="{% static 'assets/plugins/jquery/jquery-3.3.1.min.js' %}"></script>

  <script src="{% static 'assets/js/scripts.js' %}"></script>


  <script src="{% static 'assets/js/login-register.js' %}"></script>
  <script type="text/javascript" src="{% static 'assets/js/jquery.validate.min.js' %}"></script>

  <!-- TRASLATIONS -->
  <script src="{% static 'assets/js/jquery.translate.js' %}"></script>
  <script src="{% static 'assets/languages/translations.js' %}"></script>
  <script src="{% static 'assets/js/translater.js' %}"></script>

  <!-- PAGE LEVEL SCRIPTS -->
  <script>

    /**
      Checkbox on "I agree" modal Clicked!
    **/
    jQuery("#terms-agree").click(function () {
      jQuery('#termsModal').modal('toggle');

      // Check Terms and Conditions checkbox if not already checked!
      if (!jQuery("#checked-agree").checked) {
        jQuery("input.checked-agree").prop('checked', true);
      }

    });
  </script>
  {% endblock %}

</body>

</html>

app/templates/quiz/results.html
{% extends "base.html" %}
{% block content %}
<p>Results</p>
    {% if result %}
            <p>Hi {{ result.user }}, Thanks for participating this quiz. Your score is : {{ result.score }} of {{ result.total_score }}</p>
            <p>{{ quiz.name }}</p>
    {% endif %}

    {% if answers %}
    <p> Please find the correct answers of your questions :- </p>
        <ul>
        {% for object in answers %}
            <li>{{ object.question.question_text }}</li>
            <ul>
                <li>Option A : {{ object.question.option_a }}</li>
                <li>Option B : {{ object.question.option_b }}</li>
                <li>Option C : {{ object.question.option_c }}</li>
                <li>Option D : {{ object.question.option_d }}</li>
                <li>Right Answer : {{ object.question.answer }}</li>
                <li>Your Answer : {{ object.answer }}</li>

            </ul>
        {% endfor %}
        </ul>
    {% endif %}

{% endblock %}